### ISSUE TITLE
Support gang-scheduling

### ISSUE THREAD

**Issue by everpeace** [kubeflow/chainer-operator#2]
Multi-node`ChainerJob` is expected to be scheduled as a group of pods, in other words all the pods should be scheduled at once.  [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator) support such scheduling.

we need to discuss api.  What in my mind is like this:

```
apiVersion: kubeflow.org/v1alpha1
kind: ChainerJob
metadata:
  name: examplejob-chainermn
spec:
  backend: mpi
  gangScheduling:
    # if enabled pod-disruption-budget will be created
    enabled: true
    # this overwite `schedulerName` of all the belonging pods
    schedulerName: kube-batchd
...
```
