### ISSUE TITLE
Remove gcp test infra support

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/chainer-operator#29]
Hi @kubeflow/wg-training-leads, I noticed there are many low-activity training repos.
Can I disable GCP test infra for them?
I believe for repos you keep maintaining, they have already moved to optional test infra.

https://github.com/kubeflow/community/blob/2336f10cc98b35b3812960feb8a3ab2a8df6cea0/wgs.yaml#L456-L483
```
subprojects:
  - name: caffe2-operator
  - name: chainer-operator
  - name: common
  - name: fate-operator
  - name: mpi-operator
  - name: mxnet-operator
  - name: pytorch-operator
  - name: tf-operator
  - name: xgboost-operator
```
